import sys, unicodedata, bisect
sys.stdout.reconfigure(encoding="ascii", errors="backslashreplace")

MAXCP = 0x110000

# --- category ranges for L / M / N ---
def cat_ranges(prefixes):
    ranges = []
    start = None
    last_cat = None
    for cp in range(MAXCP):
        c = unicodedata.category(chr(cp)) if cp < MAXCP else "Cn"
        in_set = any(c.startswith(p) for p in prefixes)
        if in_set and start is None:
            start = cp
        elif not in_set and start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, MAXCP - 1))
    return ranges

L = cat_ranges(("L",))
M = cat_ranges(("M",))
N = cat_ranges(("N",))

# --- ccc ranges (nonzero) ---
ccc_ranges = []
start = None; cur = 0
for cp in range(MAXCP):
    v = unicodedata.combining(chr(cp))
    if v and start is None:
        start = cp; cur = v
    elif v and start is not None and v != cur:
        ccc_ranges.append((start, cp - 1, cur)); start = cp; cur = v
    elif not v and start is not None:
        ccc_ranges.append((start, cp - 1, cur)); start = None
if start is not None:
    ccc_ranges.append((start, MAXCP - 1, cur))

# --- canonical decomposition (exclude Hangul: algorithmic) ---
HANGUL_S, HANGUL_E = 0xAC00, 0xD7A3
decomp = []      # (cp, utf8 bytes of decomposition, already recursively expanded)
compose_seen = set()
compose = []     # (c1, c2, result)
for cp in range(MAXCP):
    if HANGUL_S <= cp <= HANGUL_E:
        continue
    d = unicodedata.decomposition(chr(cp))
    if not d or d.startswith("<"):
        continue
    parts = [int(x, 16) for x in d.split()]
    # recursive expansion
    exp = []
    stack = parts[:]
    while stack:
        q = stack.pop(0)
        if not (HANGUL_S <= q <= HANGUL_E):
            dq = unicodedata.decomposition(chr(q))
            if dq and not dq.startswith("<"):
                stack = [int(x, 16) for x in dq.split()] + stack
                continue
        exp.append(q)
    decomp.append((cp, bytes().join(chr(x).encode("utf-8") for x in exp)))
    if len(parts) == 2:
        c1, c2 = parts
        if unicodedata.normalize("NFC", chr(c1) + chr(c2)) == chr(cp):
            compose.append((c1, c2, cp))

compose.sort(key=lambda x: (x[0], x[1]))

def emit(name, rows, fmt):
    out = ["static const uint32_t %s[][%d] = {" % (name, len(fmt))]
    for r in rows:
        out.append("    {%s}," % ", ".join("0x%xu" % v if isinstance(v, int) else "0x%su" % v for v in r))
    out.append("};")
    return "\n".join(out)

# decompose: store (cp, offs, len) into a packed utf-8 blob
dblob = bytearray()
drows = []
for cp, b in decomp:
    drows.append((cp, len(dblob), len(b)))
    dblob.extend(b)

hdr = []
hdr.append("/* generated by tools/gen_unicode_tables.py - do not edit */")
hdr.append("#ifndef Q35_UNICODE_TABLES_H")
hdr.append("#define Q35_UNICODE_TABLES_H")
hdr.append("#include <stdint.h>")
for name, rows in (("CL", L), ("CM", M), ("CN", N)):
    hdr.append("#define Q35_%s_N %d" % (name, len(rows)))
    hdr.append(emit("q35_cat_" + name, rows, ("s", "e")))
hdr.append("")
hdr.append("#define Q35_CCC_N %d" % len(ccc_ranges))
hdr.append(emit("q35_ccc", ccc_ranges, ("s", "e", "v")))
hdr.append("")
hdr.append("#define Q35_DECOMP_N %d" % len(drows))
hdr.append("#define Q35_DECOMP_BYTES %d" % len(dblob))
hdr.append(emit("q35_decomp", drows, ("cp", "off", "len")))
hdr.append("static const uint8_t q35_decomp_bytes[Q35_DECOMP_BYTES ? Q35_DECOMP_BYTES : 1] = {")
bh = ", ".join("0x%02x" % b for b in dblob)
hdr.append(bh)
hdr.append("};")
hdr.append("")
hdr.append("#define Q35_COMPOSE_N %d" % len(compose))
hdr.append(emit("q35_compose", compose, ("c1", "c2", "r")))
hdr.append("#endif")
open("src/q35_unicode_tables.h", "w", newline="\n").write("\n".join(hdr) + "\n")
print("L ranges", len(L), "M", len(M), "N", len(N))
print("ccc ranges", len(ccc_ranges), "decomp", len(drows), "bytes", len(dblob), "compose", len(compose))
